# Generated by Django 5.2.4 on 2025-07-23 22:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_rename_phone_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationcode",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
