# Generated by Django 5.2.4 on 2025-07-23 23:07

import account.generators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_verificationcode_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_code",
            field=models.CharField(
                default=account.generators.generate_referral_code,
                max_length=6,
                unique=True,
            ),
        ),
    ]
