# Generated by Django 5.2.4 on 2025-07-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_remove_user_is_verified"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-id"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterModelOptions(
            name="verificationcode",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Verification Code",
                "verbose_name_plural": "Verification Codes",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="referral_code",
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["phone_number"], name="account_use_phone_n_ed0b53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["referral_code"], name="account_use_referra_293b80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["referrer"], name="account_use_referre_1b316c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationcode",
            index=models.Index(
                fields=["created_at"], name="account_ver_created_b5b62a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationcode",
            index=models.Index(
                condition=models.Q(("is_blocked", False)),
                fields=["user", "code", "created_at"],
                name="idx_active_codes",
            ),
        ),
    ]
