# Generated by Django 5.2.4 on 2025-07-25 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0007_alter_user_options_alter_verificationcode_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="verificationcode",
            name="idx_active_codes",
        ),
    ]
